### ISSUE TITLE
Unlink option is missing when part of a link selected

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#141]
![jul-20-2017 12-36-13](https://user-images.githubusercontent.com/156149/28413510-147ea254-6d48-11e7-93d6-3837ac5878d2.gif)

**Comment by Reinmar** [comment]
This is serious because you can't type after a link now so the only option to do that was to type and then unlink part of that.

**Comment by oleq** [comment]
I'm wondering which part of https://github.com/ckeditor/ckeditor5-link/blob/master/src/unlinkcommand.js#L40-L41 has failed 🤔

**Comment by Reinmar** [comment]
You mean rather https://github.com/ckeditor/ckeditor5-link/blob/master/src/unlinkcommand.js#L23. The command isn't even executed.

**Comment by oleq** [comment]
Yes, you're right. It's funny `selection.hasAttribute()` fails to discover the attribute in such boundary case. Maybe something's wrong with editing<->model synchronization?

**Comment by Reinmar** [comment]
Doesn't look like it still:

![image](https://user-images.githubusercontent.com/156149/28419305-d08b5b70-6d5e-11e7-84f6-a0bdf2c416ec.png)

**Comment by oleq** [comment]
The presence of the unlink button is controlled by the [`_getSelectedLinkElement`](https://github.com/ckeditor/ckeditor5-link/blob/master/src/link.js#L248-L251), which works fine for the balloon as a whole (showing up on "click", positioning, etc.) because it checks if the [link is fully selected and otherwise returns `null`](https://github.com/ckeditor/ckeditor5-link/blob/master/src/link.js#L387).

What we need to do is connect the presence of the unlink button with the state of the unlink command.
