### ISSUE TITLE
Form component

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-link#16]
What do you think about creating something as `Form` component (regular `<form></form>` in HTML). It will be wrapper for form fields and buttons. It'll give us possibility to handle submit event (solves submitting for pressing <kbd>Enter</kbd> and clicking button by one listener) or use HTML form validation.

It also might be useful in the feature when we will be working on custom validation.

Right now we keep form controls inside `<div />` and we have to handle click on submit button and <kbd>Enter</kbd> press separately.

**Comment by Reinmar** [comment]
Sounds like a good plan. But this ticket needs to be moved to ckeditor5-ui-default.

**Comment by oleq** [comment]
While I'm totally OK with it in general – in fact this is the only right way to deal with forms in the long run – it could be not quite necessary yet.

It feels like an overkill at the current stage of development because it will take time to implement it and there's only one clear use–case for it ATM (link). Let's discuss it in ckeditor5-ui-default and find out what is needed to implement the form component.

**Comment by oskarwrobel** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-ui-default/issues/54
