### ISSUE TITLE
Balloon panel doesn't show up after click when link is not highlighted

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-link#176]
![mar-08-2018 13-35-21](https://user-images.githubusercontent.com/1057056/37151615-7ba0b708-22d6-11e8-8cea-42f178febbb2.gif)

**Comment by szymonkups** [comment]
I've tested this a little and it looks like this is because highlight's `<span>` element is created on top of `<a>` element. The failing flow is like this:
1. User clicks on a link,
2. `selectionchange` event is fired before click event, it triggers changes on the model,
3. Postfixer is adding marker over link,
4. Marker is rendered as `<span>` over `<a>` element and Renderer is creating brand new `<a>` in the DOM,
5. No click event since old `<a>` is removed from DOM.

We will fix this by adding highlight with higher priority than link one, so the `<span>` will be rendered inside `<a>` element.

**Comment by Reinmar** [comment]
The PR proposed by @szymonkups in https://github.com/ckeditor/ckeditor5-link/pull/179 was a workaround which changed how the highlight is rendered. From:

```html
<span class=highlight><a href=#>xxx</a></span>
```

To:

```html
<a href=#><span class=highlight>xxx</span></a>
```

It fixes this issue in Chrome, but:

* it's still broken in Firefox and Safari,
* new issues appear.

However, most importantly, it's still wrong – the highlight must not be rendered as a separate span. It should be a class on the original `<a>` element. Toggling a class will be much safer than changing the DOM structure.

Unfortunately, [switching to a class-based highlight](https://github.com/ckeditor/ckeditor5-link/issues/180) is blocked now by a much bigger issue. Therefore, we won't manage to fix this issue before releasing beta.1.

So, I think that we should still go with the highlight on and live with this bug for a while. It definitely needs to be fixed before the first stable release and it's definitely quite critical. However, we also need to be able to see how the link highlight feature behaves – it's better not to add it like that in a final release.
