### ISSUE TITLE
Ctrl+K should open link URL editing dialog

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#181]
1. http://localhost:8125/ckeditor5-core/tests/manual/article.html
2. Click the link. Link balloon appears.
3. Press <kbd>Ctrl</kbd>+<kbd>K</kbd>.

Expected: something could happen.

Actually: nothing happens.

---

Another scenario:

1. http://localhost:8125/ckeditor5-core/tests/manual/article.html
2. Click next to the link. Press arrow keys to navigate into the link.
3. Press <kbd>Ctrl</kbd>+<kbd>K</kbd>.
4. The link balloon appears.

How to start editing the link now? You need to <kbd>Tab</kbd> to the "edit link" button and press <kbd>Enter</kbd>.

---

I think that both these cases would benefit if <kbd>Ctrl</kbd>+<kbd>K</kbd> press *when the link balloon is visible*, would switch to the link URL editing balloon.

**Comment by Reinmar** [comment]
cc @oleq @dkonopka

**Comment by dkonopka** [comment]
Agree that first scenario should open editing balloon (if it's opened), but TBH I'm not sure to turn on this step in the second scenario (what if someone wants to open link in the new tab instead of editing it? Users needs to go "check" button, it's not so intuitive. )

On the other hand, would be great if the behavior of shortcut <kbd>Ctrl</kbd>+<kbd>K</kbd>will be always the same (activating edit step).
