### ISSUE TITLE
Remove the "unlink" button from the toolbar

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-link#52]
The unlinking feature is already available in the link editing ballon. This is great, because we can have one less button in the toolbar. The less, the better.

**Comment by Reinmar** [comment]
I totally agree, but it looks like a ticket for specific usage. E.g. ckeditor5.gihtub.io. Or do you mean to remove the button totally?

**Comment by fredck** [comment]
Yes, I would remove it totally. It can be brought back later on as an optional feature, if necessary, but let's wait and see if it makes sense.

**Comment by oskarwrobel** [comment]
It is already optional https://github.com/ckeditor/ckeditor5-link/blob/master/tests/manual/link.js#L12

**Comment by Reinmar** [comment]
> Yes, I would remove it totally. It can be brought back later on as an optional feature, if necessary, but let's wait and see if it makes sense

It may make sense for one thing – you could be able to do ctrl+a and unlink everything. Quite an edge case though.

**Comment by fredck** [comment]
> It is already optional https://github.com/ckeditor/ckeditor5-link/blob/master/tests/manual/link.js#L12

Well, everything that goes in the toolbar is optional... but not really:
https://github.com/ckeditor/ckeditor5-link/blob/master/src/link.js#L88-L117

The above code is always executed:
https://github.com/ckeditor/ckeditor5-link/blob/master/src/link.js#L52

Which means that, although we don't want to have it by default, we'll have to keep maintaining it.

If we would ever bring it, it should be "really" optional, like having to load additional features or modules to have it available.

Ofc, we may be wrong here and have to revert the code cleanup related to that. Still I would prefer to not have such code, because later on we'll never be able to remove it.

**Comment by fredck** [comment]
> It may make sense for one thing – you could be able to do ctrl+a and unlink everything. Quite an edge case though.

Indeed an edge case. In any case, I would predict a keystroke combination to execute unlink.

**Comment by Reinmar** [comment]
> If we would ever bring it, it should be "really" optional, like having to load additional features or modules to have it available.

+1

**Comment by Reinmar** [comment]
I've just realised one thing. Since you cannot escape link when typing at the end of it, you'll often need to remove link from a piece of a text. This is pretty cumbersome now:

<img width="733" alt="screen shot 2016-10-29 at 13 18 14" src="https://cloud.githubusercontent.com/assets/156149/19829168/3334524a-9dda-11e6-8ade-8d6aa18832b9.png">

As you can see, there's no link balloon in this case. You can either click the unlink button in the toolbar or open the link balloon and remove the link from there but this is counterintuitive.

So, I'm a bit unsure now about removing the button. The unlink option must be better exposed and/or we must work on escaping link at its right boundary (e.g. implement Firefox's left/right arrow key behaviour).

**Comment by fredck** [comment]
I would, in any case, have no button at the first release. It's easy to bring it in later on.

My point is that, although cumbersome, users will be able to fix the link somehow. Hopefully, this is not an extremely common situation and the benefits of a less bloated toolbar will overcome the disadvantages caused by it.

**Comment by Reinmar** [comment]
The unlink button was mentioned in a Twitter:

![image](https://cloud.githubusercontent.com/assets/156149/25014144/d446511e-2076-11e7-91ed-7e88515408ae.png)

I'm curious for more opinions on how important is the ability to remove a couple of links at once.

**Comment by oleq** [comment]
@Reinmar It could be a problem if we don't provide "Remove formatting" feature. You may want to paste a lengthy chunk of text from the clipboard and use it as a quote but there's a lot of formatting you'd rather see removed because it obscures the meaning of the text. But it still passes the filtering and it's a valid content in the editor.

ATM you can do <kbd>CTRL</kbd>+<kbd>A</kbd> + 2 * <kbd>CTRL</kbd>+<kbd>B</kbd> to remove all bolds, italics, etc. but once we get rid of the "Unlink" button, you will need to spend a lot of time to clean-up the content from links. Imagine it was a paragraph from the Wikipedia where almost every single word is a link.

Alternatively... we can provide some fancy shortcut like <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>V</kbd> to paste plain text. Then, we can get rid of "Unlink" without any issue, I think.

**Comment by Reinmar** [comment]
Let's have a final decision:

* 👍  for: Remove the "Unlink" button from the toolbar.
* 👎 for: Extend its functionality to strip all links in the selection (as described in https://github.com/ckeditor/ckeditor5-link/issues/52#issuecomment-293949650).

**Comment by oskarwrobel** [comment]
Unlink button in toolbar might also help when you want to remove link which is split by block elements.

![jul-06-2017 13-07-53](https://user-images.githubusercontent.com/1057056/27908450-2bf3524c-624c-11e7-8f5a-08a9587e4ffe.gif)

BTW BPV position is very strange when is attached to the multi line selection.

**Comment by oleq** [comment]
> BTW BPV position is very strange when is attached to the multi line selection.

It **could** improve after https://github.com/ckeditor/ckeditor5-utils/issues/168.

**Comment by oleq** [comment]
> Extend its functionality to strip all links in the selection (as described in #52 (comment)).

@Reinmar: Doesn't it work like this already?

**Comment by oskarwrobel** [comment]
Unlink button is disabled when selection contains more than link elements.

**Comment by oleq** [comment]
So it seems some things have changed since I posted this https://twitter.com/anowodzinski/status/852116748518252544. 

I'm for moving the unlink button to the balloon panel then. In the future, we could offer it in the toolbar as an item of a stacked button (drop-button with an arrow), cleaning all links in the selection.

So what I think we should do now:
1. Remove the unlink button from the toolbar.
2. Implement the unlink button in the balloon.
3. Make sure it cleans all the links in the selection so when we add it back to the toolbar in a space–smart way, it's ready to use.

Future:
1. Implement a UI component grouping the buttons in the form of a dropdown 
![image](https://user-images.githubusercontent.com/1099479/27910293-ca2be228-6254-11e7-9d63-620cfaa40756.png)

2. Put unlink button there.

**Comment by Reinmar** [comment]
> Implement the unlink button in the balloon.

It's already there. You mean – enable it by default?

> Make sure it cleans all the links in the selection so when we add it back to the toolbar in a space–smart way, it's ready to use.

Not necessary now.

I'd do the  simplest thing for now and simply remove it from the toolbar and component factory. The rest can be moved to a followup. It's not very intuitive for the unlink button in the link balloon to be on when you're not in a link yet anyway, so this wouldn't be a perfect solution either.

**Comment by oleq** [comment]
> It's already there. You mean – enable it by default?

I suppose I should see my eye doctor 😉. No, I'd leave it as it is, visible only when editing existing link.

> I'd do the simplest thing for now and simply remove it from the toolbar and component factory. The rest can be moved to a followup. It's not very intuitive for the unlink button in the link balloon to be on when you're not in a link yet anyway, so this wouldn't be a perfect solution either.

👍
