### ISSUE TITLE
Make the link balloon wider

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-link#56]
Currently you can see only small fragment of the URL. We won't be able to make the balloon so wide to fit a whole long URL, but I found that I wished that the input was ~150%-200% of the current size.

**Comment by fredck** [comment]
The current design is pleasant and seems to do its job. I feel this change as unnecessary at this stage.

**Comment by Reinmar** [comment]
Did you work with the link panel? You cannot see what you're linking to:

<img width="778" alt="screen shot 2016-10-26 at 17 37 01" src="https://cloud.githubusercontent.com/assets/156149/19732972/da41c764-9ba2-11e6-8384-f5cb04efe230.png">

This is a simple, quite short, link to MDN I can't see it. The input is so narrow that when I move caret to the end of the link I don't see the beginning so I don't know if I haven't missed something (e.g pasted it twice). Being nearly unable to verify what's in there is really irritating.

**Comment by Reinmar** [comment]
We've got plenty of space on the screen. I don't understand why can't we use more.

**Comment by fredck** [comment]
What you suggest will not solve the problem anyway, because links can, and usually are, big enough to still not fit (take an average link from medium, for example).

There are other UX concerns that you're not taking in consideration. The distance between the balloon connection to the link, the start of the text field and the save button will change. All this changes the usability of the balloon.

Additionally, it's a matter of UI decision, to make it look good as well. I assume the designer wanted to make it look like that.

Anyway, that's just my opinion. Any way is good for me. I just feel that we have to try to do less.

**Comment by oleq** [comment]
> I assume the designer wanted to make it look like that.

👍 

TBH, I'm also against it. To keep long links visible, we'd need to make the panel twice as big. And even then, we wouldn't fix it for all cases. Usually, you just paste a link there and forget about it. Re–editing link is seldom performed.

What we actually need is an ability to open the link https://github.com/ckeditor/ckeditor5-link/issues/31.

**Comment by Reinmar** [comment]
I guess this is enough of "no" :D. Closing. Thanks.
